import Vue from 'vue'
import {
  Button,
  Form,
  FormItem,
  Input,
  Message,
  Container,
  Header,
  Aside,
  Main,
  Menu,
  Submenu,
  MenuItem,
  Breadcrumb,
  BreadcrumbItem,
  Card,
  Row,
  Col,
  Table,
  TableColumn,
  Switch,
  Tooltip,
  Pagination,
  Dialog,
  Link,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  DatePicker,
  Upload,
  MessageBox,
  Progress,
  Select,
  Option,
  Image,
  InfiniteScroll,
  CarouselItem,
  Carousel,
  Slider
} from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Link)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(DatePicker)
Vue.use(Upload)
Vue.use(Progress)
Vue.use(Select)
Vue.use(Option)
Vue.use(Image)
Vue.use(InfiniteScroll)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Slider)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
